export const TOGGLE_UNITS = 'TOGGLE_UNITS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const SHOW_DETAILS = 'SHOW_DETAILS';
export const HIDE_DETAILS = 'HIDE_DETAILS';
export const TOGGLE_ADD = 'TOGGLE_ADD';
export const UPDATE_WEATHER = 'UPDATE_WEATHER';
export const LOAD_LOCATIONS = 'LOAD_LOCATIONS';
